In [1]:
import pandas as pd
import os

In [2]:
import pandas as pd
import numpy as np
from collections import Counter

In [3]:
df = pd.read_csv('anthrokids.csv')

In [4]:
os.getcwd()

'C:\\Users\\anagh\\OneDrive\\Desktop\\python'

In [5]:
df

,id,mass,height,waist,foot,sittingHeight,upperLegLength,kneeHeight,forearmLength,age,gender,handedness,birthOrder
0,1,15.5,103.3,47.5,16.3,582.0,306.0,NaN,259.0,4.219,F,right,1.0
1,2,17.6,103.9,49.8,16.3,606.0,311.0,NaN,274.0,4.326,M,right,1.0
2,3,23.0,111.2,52.0,17.1,594.0,387.0,NaN,304.0,4.476,F,right,1.0
3,4,16.5,99.7,49.1,16.3,542.0,312.0,NaN,281.0,3.841,F,both,1.0
4,5,15.0,99.7,46.5,16.7,524.0,321.0,NaN,269.0,3.460,F,both,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,91096,16.0,103.6,48.7,16.5,597.0,307.0,307.0,269.0,3.403,M,both,2.0
3896,91097,14.3,99.9,46.0,15.1,582.0,291.0,275.0,253.0,3.397,M,left,4.0
3897,91099,12.4,90.5,47.6,14.1,537.0,289.0,254.0,224.0,2.442,F,right,1.0
3898,91100,18.4,100.7,55.1,16.1,570.0,320.0,303.0,273.0,4.188,M,right,1.0
3899,91095,25.5,124.4,57.0,19.9,703.0,383.0,378.0,322.0,4.974,M,left,1.0

In [6]:
print(df.age)

0       4.219
1       4.326
2       4.476
3       3.841
4       3.460
        ...
3895    3.403
3896    3.397
3897    2.442
3898    4.188
3899    4.974
Name: age, Length: 3900, dtype: float64

In [8]:
#function to round integer values


def rounding(age):
    vals = str(age).split('.')
    if (int(vals[1][0])>=5):
        vals[0] = int(vals[0])+1
    else:
        pass
    return(int(vals[0]))

In [13]:
df1=  df[df['age'].isnull()]

In [14]:
df1.head()

,id,mass,height,waist,foot,sittingHeight,upperLegLength,kneeHeight,forearmLength,age,gender,handedness,birthOrder
1029,15034,44.8,154.7,60.3,21.4,838.0,519.0,468.0,402.0,NaN,M,NaN,NaN
1402,22023,15.0,94.4,51.1,15.2,563.0,285.0,271.0,253.0,NaN,M,NaN,NaN

In [20]:
df.dropna(subset=['age'],inplace = True)   # remove null values from the original data frame.

In [27]:
# integrating the rounding function to the Age column to get rounded age values
age_list = []
for i in df.age:
    if(type(i)!= float): # code to check if it's an integer. if it is, then no need to round it.
        age_list.append(i)
    else:
        age_list.append(rounding(i))

print(age_list)

[4, 4, 4, 4, 3, 4, 3, 4, 6, 5, 5, 14, 14, 14, 13, 13, 13, 13, 12, 14, 13, 13, 12, 13, 13, 12, 14, 14, 12, 12, 14, 12, 13, 13, 14, 13, 14, 14, 14, 14, 13, 14, 13, 14, 14, 13, 14, 14, 13, 12, 12, 13, 10, 10, 6, 7, 12, 6, 5, 9, 9, 10, 7, 7, 11, 9, 8, 7, 8, 9, 8, 8, 7, 12, 5, 7, 7, 5, 8, 9, 9, 8, 11, 10, 10, 11, 12, 11, 11, 10, 10, 11, 13, 11, 12, 11, 11, 12, 12, 12, 10, 9, 10, 10, 11, 10, 10, 11, 11, 12, 12, 5, 16, 17, 17, 18, 18, 17, 19, 17, 17, 17, 19, 18, 16, 15, 15, 17, 17, 15, 14, 15, 16, 17, 17, 16, 16, 16, 18, 18, 16, 16, 17, 18, 16, 16, 15, 15, 17, 16, 16, 20, 15, 17, 15, 14, 15, 16, 15, 19, 16, 17, 16, 17, 14, 16, 18, 16, 17, 18, 15, 5, 4, 5, 4, 3, 4, 4, 4, 6, 8, 9, 8, 8, 6, 7, 6, 8, 8, 9, 7, 7, 7, 6, 6, 8, 6, 6, 6, 7, 7, 9, 8, 7, 7, 10, 8, 8, 8, 8, 7, 6, 8, 8, 9, 7, 6, 6, 7, 8, 9, 7, 9, 6, 7, 7, 6, 5, 6, 7, 6, 4, 5, 5, 5, 4, 3, 3, 3, 4, 6, 5, 4, 6, 3, 4, 4, 5, 4, 4, 5, 5, 5, 4, 4, 5, 4, 4, 3, 3, 4, 4, 5, 5, 5, 4, 3, 5, 5, 8, 8, 12, 18, 17, 13, 14, 14, 16, 18, 13, 7, 5, 5, 14, 15, 14, 14, 12, 4, 6, 13, 7, 8, 10, 10, 11, 11, 12, 11, 9, 10, 6, 8, 6, 6, 12, 12, 7, 6, 9, 9, 6, 5, 9, 5, 7, 13, 11, 2, 6, 3, 10, 8, 5, 14, 14, 10, 12, 2, 5, 10, 10, 10, 8, 8, 8, 11, 11, 10, 11, 11, 9, 9, 9, 6, 6, 7, 6, 7, 6, 5, 7, 7, 9, 9, 10, 11, 11, 9, 7, 9, 8, 8, 9, 9, 9, 9, 9, 8, 12, 11, 6, 6, 6, 7, 7, 7, 8, 11, 11, 10, 10, 7, 7, 10, 10, 9, 10, 5, 6, 8, 8, 12, 13, 7, 6, 9, 11, 12, 12, 11, 13, 9, 7, 6, 5, 14, 14, 13, 10, 7, 10, 14, 13, 13, 13, 11, 11, 13, 14, 13, 13, 12, 13, 11, 11, 12, 13, 12, 8, 8, 9, 10, 11, 9, 10, 10, 10, 12, 7, 7, 12, 13, 13, 11, 11, 10, 12, 9, 9, 7, 7, 11, 11, 11, 11, 6, 6, 12, 12, 10, 11, 6, 5, 7, 6, 6, 9, 10, 5, 6, 10, 11, 11, 8, 8, 12, 6, 5, 5, 5, 5, 6, 6, 6, 8, 4, 6, 5, 5, 4, 8, 8, 9, 10, 12, 7, 8, 7, 10, 12, 12, 11, 12, 6, 7, 8, 11, 11, 12, 11, 12, 12, 11, 14, 14, 14, 15, 14, 14, 14, 14, 13, 13, 13, 13, 13, 14, 13, 14, 14, 14, 14, 12, 11, 12, 12, 12, 7, 6, 10, 10, 12, 5, 11, 8, 8, 11, 6, 6, 8, 7, 8, 9, 9, 9, 11, 11, 12, 11, 10, 11, 10, 5, 6, 7, 7, 11, 11, 11, 6, 10, 11, 9, 8, 10, 11, 10, 11, 9, 11, 10, 11, 10, 7, 12, 12, 6, 5, 6, 7, 10, 11, 7, 7, 9, 10, 11, 12, 6, 10, 9, 10, 10, 10, 10, 11, 10, 9, 9, 9, 7, 8, 8, 8, 9, 10, 9, 10, 10, 9, 10, 11, 10, 10, 3, 6, 6, 5, 4, 2, 3, 3, 5, 2, 4, 4, 4, 2, 3, 2, 3, 4, 4, 4, 5, 4, 4, 2, 2, 2, 4, 4, 3, 4, 3, 4, 3, 2, 3, 2, 3, 2, 13, 13, 14, 14, 13, 14, 13, 14, 13, 13, 12, 15, 13, 14, 15, 14, 13, 13, 14, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 5, 4, 4, 5, 5, 4, 2, 4, 4, 3, 6, 6, 3, 2, 2, 3, 3, 3, 4, 3, 3, 3, 6, 5, 18, 18, 18, 18, 16, 17, 17, 15, 18, 17, 18, 17, 15, 15, 16, 16, 15, 14, 16, 15, 16, 14, 15, 15, 18, 16, 15, 14, 16, 17, 15, 15, 15, 16, 18, 18, 17, 17, 17, 16, 18, 19, 17, 16, 15, 15, 18, 17, 15, 14, 14, 14, 14, 14, 13, 12, 14, 15, 14, 13, 12, 13, 12, 12, 14, 13, 13, 14, 12, 13, 13, 7, 7, 7, 7, 7, 7, 8, 8, 6, 6, 7, 8, 7, 8, 12, 12, 12, 11, 9, 9, 9, 9, 9, 9, 9, 9, 11, 10, 11, 10, 10, 10, 6, 7, 15, 16, 15, 17, 14, 15, 15, 16, 9, 8, 8, 11, 11, 11, 7, 9, 7, 7, 7, 7, 17, 15, 15, 17, 18, 15, 15, 15, 15, 14, 16, 15, 14, 15, 15, 16, 15, 15, 15, 15, 17, 14, 15, 18, 16, 18, 12, 11, 16, 19, 18, 18, 17, 18, 18, 16, 17, 16, 16, 19, 18, 18, 17, 17, 17, 17, 18, 17, 17, 18, 17, 18, 18, 17, 19, 19, 18, 17, 9, 11, 11, 7, 9, 12, 11, 12, 9, 8, 18, 9, 9, 10, 9, 9, 10, 17, 16, 16, 17, 17, 16, 16, 18, 17, 15, 16, 18, 18, 17, 16, 15, 15, 16, 15, 17, 15, 17, 16, 16, 15, 17, 16, 15, 16, 15, 15, 15, 16, 16, 17, 17, 19, 17, 17, 16, 15, 15, 15, 15, 15, 16, 15, 17, 16, 16, 16, 16, 14, 14, 13, 12, 12, 13, 13, 13, 12, 13, 14, 12, 13, 14, 13, 14, 13, 12, 15, 14, 12, 12, 13, 13, 10, 12, 12, 12, 11, 10, 9, 12, 10, 10, 11, 10, 10, 11, 18, 19, 18, 18, 7, 7, 16, 11, 13, 8, 7, 16, 17, 16, 18, 17, 16, 9, 9, 10, 11, 16, 16, 15, 13, 15, 12, 13, 14, 13, 12, 12, 16, 13, 12, 14, 13, 13, 13, 14, 6, 6, 7, 6, 6, 8, 8, 8, 8, 8, 8, 9, 7, 7, 7, 9, 9, 10, 13, 15, 13, 13, 13, 15, 14, 16, 13, 12, 12, 13, 13, 14, 13, 13, 13, 14, 15, 14, 14, 14, 13, 13, 15, 15, 14, 14, 14, 15, 15, 15, 15, 14, 14, 13, 13, 15, 13, 14, 14, 14, 13, 15, 14, 14, 15, 15, 15, 13, 13, 13, 13, 13, 13, 13, 14, 13, 15, 15, 15, 17, 15, 15, 13, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 15, 15, 13, 10, 10, 10, 11, 10, 11, 10, 10, 8, 6, 6, 7, 10, 11, 11, 11, 12, 8, 10, 9, 12, 11, 11, 11, 12, 11, 7, 6, 9, 9, 8, 8, 8, 6, 7, 9, 9, 9, 10, 11, 10, 11, 10, 7, 6, 8, 9, 8, 9, 7, 7, 7, 9, 9, 10, 10, 10, 7, 7, 7, 7, 9, 6, 6, 6, 9, 9, 9, 9, 9, 7, 8, 7, 8, 7, 7, 9, 9, 7, 6, 8, 8, 11, 12, 13, 6, 7, 7, 15, 15, 17, 15, 15, 15, 15, 18, 10, 10, 10, 18, 8, 8, 9, 9, 9, 11, 11, 10, 12, 9, 11, 11, 8, 14, 12, 12, 14, 13, 13, 13, 13, 13, 13, 14, 12, 13, 12, 12, 13, 14, 14, 13, 13, 12, 14, 12, 14, 14, 15, 15, 11, 13, 14, 16, 18, 17, 17, 18, 17, 16, 17, 18, 19, 18, 9, 8, 7, 6, 11, 11, 11, 11, 11, 12, 13, 14, 13, 12, 12, 12, 13, 13, 13, 13, 13, 15, 14, 14, 12, 12, 14, 13, 12, 12, 12, 13, 12, 14, 12, 14, 14, 12, 12, 13, 13, 13, 14, 15, 13, 15, 13, 13, 14, 13, 12, 12, 14, 13, 7, 7, 7, 8, 8, 7, 8, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 7, 12, 11, 6, 6, 10, 15, 15, 15, 14, 14, 13, 14, 15, 15, 15, 15, 15, 14, 13, 15, 14, 5, 5, 5, 5, 5, 5, 4, 4, 4, 3, 4, 6, 4, 6, 5, 5, 3, 4, 4, 3, 6, 6, 6, 5, 5, 4, 4, 4, 3, 4, 3, 6, 5, 4, 5, 6, 5, 5, 5, 4, 5, 2, 3, 7, 7, 6, 9, 5, 5, 4, 4, 4, 5, 6, 5, 12, 12, 11, 11, 11, 11, 11, 11, 11, 6, 6, 12, 7, 10, 10, 9, 11, 9, 9, 11, 11, 11, 11, 11, 11, 9, 7, 9, 6, 6, 7, 7, 7, 9, 9, 8, 6, 6, 6, 9, 9, 11, 11, 11, 10, 10, 10, 10, 10, 10, 8, 9, 8, 7, 7, 7, 8, 11, 8, 4, 4, 5, 5, 7, 9, 6, 7, 2, 3, 3, 4, 4, 4, 4, 3, 2, 5, 6, 5, 6, 4, 4, 5, 4, 3, 3, 13, 14, 14, 15, 13, 14, 17, 17, 16, 14, 11, 15, 16, 17, 17, 18, 16, 15, 15, 16, 12, 15, 15, 16, 14, 15, 15, 12, 15, 13, 12, 12, 12, 13, 13, 11, 15, 16, 18, 12, 12, 13, 11, 12, 7, 12, 13, 11, 14, 13, 12, 13, 13, 13, 13, 12, 12, 13, 13, 13, 13, 13, 13, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 13, 13, 13, 14, 14, 14, 14, 15, 14, 13, 13, 13, 13, 14, 14, 14, 13, 13, 13, 14, 14, 13, 15, 16, 14, 14, 15, 14, 13, 13, 13, 14, 13, 14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 14, 13, 13, 16, 15, 13, 11, 12, 11, 12, 11, 12, 12, 16, 12, 12, 17, 13, 13, 11, 10, 10, 10, 10, 9, 8, 11, 11, 11, 12, 11, 11, 11, 11, 11, 10, 8, 5, 7, 11, 11, 12, 13, 14, 11, 13, 15, 12, 12, 11, 7, 11, 13, 12, 17, 13, 13, 16, 15, 16, 17, 17, 15, 16, 16, 17, 16, 17, 16, 17, 6, 9, 4, 3, 5, 4, 5, 3, 7, 6, 3, 5, 5, 3, 6, 4, 5, 5, 3, 3, 2, 5, 5, 4, 4, 4, 5, 6, 4, 5, 4, 6, 5, 2, 3, 2, 3, 3, 5, 5, 3, 3, 2, 5, 3, 4, 5, 5, 5, 3, 5, 6, 4, 6, 6, 8, 5, 5, 4, 4, 4, 4, 5, 5, 2, 2, 6, 5, 4, 3, 4, 3, 4, 3, 5, 8, 5, 4, 6, 6, 5, 4, 5, 5, 5, 8, 6, 6, 6, 4, 16, 15, 15, 15, 15, 16, 14, 13, 15, 12, 14, 11, 14, 8, 9, 11, 12, 12, 12, 13, 14, 14, 14, 11, 12, 11, 12, 12, 13, 13, 16, 14, 14, 16, 11, 10, 13, 12, 18, 17, 15, 14, 6, 6, 5, 5, 6, 3, 7, 6, 5, 6, 12, 16, 16, 18, 16, 5, 11, 16, 6, 14, 14, 13, 14, 10, 10, 10, 10, 11, 12, 15, 11, 9, 8, 15, 15, 15, 3, 5, 12, 12, 13, 12, 11, 11, 17, 17, 9, 9, 10, 8, 9, 3, 2, 16, 17, 14, 17, 15, 15, 17, 12, 12, 13, 12, 17, 16, 17, 18, 17, 16, 16, 17, 17, 17, 12, 12, 13, 13, 12, 12, 17, 17, 17, 18, 17, 16, 17, 16, 15, 15, 16, 12, 12, 12, 13, 15, 16, 15, 14, 15, 14, 14, 14, 14, 17, 14, 14, 13, 14, 14, 13, 13, 13, 9, 12, 11, 11, 12, 11, 12, 12, 11, 14, 10, 9, 12, 12, 12, 11, 12, 11, 10, 12, 11, 9, 11, 11, 12, 11, 9, 10, 11, 10, 10, 10, 10, 10, 10, 12, 10, 11, 16, 15, 15, 16, 16, 18, 17, 17, 17, 17, 16, 17, 17, 18, 17, 16, 16, 17, 17, 17, 16, 17, 18, 17, 16, 17, 18, 18, 18, 18, 18, 18, 18, 18, 16, 17, 17, 18, 18, 16, 18, 17, 16, 15, 18, 17, 16, 18, 17, 17, 16, 16, 15, 16, 15, 18, 16, 17, 17, 16, 16, 16, 16, 16, 16, 16, 17, 16, 17, 16, 16, 16, 16, 16, 16, 17, 16, 15, 14, 15, 15, 13, 13, 15, 12, 17, 17, 17, 16, 17, 17, 13, 12, 12, 12, 12, 11, 13, 11, 12, 12, 10, 9, 12, 10, 10, 10, 10, 11, 12, 10, 11, 13, 9, 10, 9, 10, 9, 10, 15, 15, 15, 13, 14, 9, 10, 9, 10, 13, 14, 11, 12, 12, 12, 12, 12, 12, 11, 10, 8, 9, 8, 12, 12, 11, 11, 13, 12, 12, 17, 17, 10, 15, 11, 11, 12, 9, 12, 10, 10, 12, 12, 12, 9, 10, 11, 11, 13, 13, 13, 13, 9, 11, 13, 11, 10, 11, 12, 12, 12, 13, 13, 9, 9, 10, 17, 16, 16, 17, 16, 16, 17, 17, 17, 18, 15, 15, 15, 14, 18, 18, 17, 15, 15, 16, 18, 14, 13, 13, 13, 11, 11, 11, 12, 10, 10, 9, 10, 9, 8, 11, 12, 11, 12, 11, 11, 12, 11, 11, 8, 9, 9, 9, 9, 10, 9, 9, 8, 9, 9, 5, 5, 7, 7, 7, 8, 7, 6, 6, 6, 6, 7, 7, 8, 7, 7, 6, 5, 7, 7, 12, 8, 9, 6, 6, 9, 8, 15, 13, 15, 14, 13, 13, 13, 12, 14, 13, 12, 15, 15, 15, 14, 15, 15, 15, 15, 14, 13, 13, 13, 13, 13, 13, 14, 14, 15, 14, 15, 15, 17, 14, 15, 15, 15, 15, 16, 16, 15, 15, 16, 15, 15, 15, 16, 16, 16, 18, 18, 17, 17, 17, 18, 17, 17, 17, 18, 18, 18, 18, 18, 18, 17, 17, 18, 15, 15, 19, 18, 10, 11, 9, 9, 9, 10, 9, 9, 10, 9, 8, 7, 6, 7, 8, 10, 7, 6, 6, 6, 5, 7, 6, 6, 6, 6, 8, 6, 6, 7, 8, 8, 7, 7, 7, 8, 7, 6, 9, 9, 12, 11, 12, 9, 12, 6, 10, 9, 7, 7, 8, 8, 8, 8, 11, 9, 12, 12, 8, 9, 11, 8, 6, 5, 9, 6, 12, 14, 13, 12, 13, 13, 13, 15, 15, 15, 14, 15, 12, 12, 12, 12, 15, 15, 16, 15, 12, 13, 13, 13, 13, 15, 13, 13, 13, 14, 14, 13, 13, 15, 15, 15, 14, 15, 14, 14, 15, 14, 14, 15, 12, 13, 15, 15, 13, 13, 15, 15, 13, 15, 18, 18, 18, 18, 19, 18, 16, 17, 18, 16, 18, 16, 18, 18, 16, 16, 18, 15, 14, 16, 18, 18, 8, 7, 10, 7, 11, 12, 13, 5, 6, 5, 6, 5, 7, 6, 7, 7, 9, 8, 12, 11, 12, 11, 11, 11, 10, 9, 10, 10, 11, 10, 11, 10, 11, 12, 10, 11, 9, 10, 8, 7, 7, 9, 6, 7, 8, 5, 7, 6, 10, 6, 7, 6, 6, 6, 6, 9, 10, 10, 9, 9, 9, 11, 11, 10, 11, 8, 9, 9, 9, 8, 8, 8, 7, 7, 7, 8, 9, 8, 8, 9, 7, 6, 6, 9, 8, 8, 8, 6, 6, 6, 6, 6, 6, 8, 3, 5, 2, 4, 2, 2, 4, 3, 4, 4, 3, 4, 5, 3, 4, 3, 3, 4, 3, 3, 2, 4, 3, 4, 4, 4, 5, 3, 3, 3, 5, 5, 4, 5, 2, 4, 4, 6, 4, 4, 2, 2, 3, 3, 4, 3, 17, 17, 17, 16, 16, 18, 16, 17, 17, 17, 18, 17, 18, 17, 17, 16, 17, 17, 18, 17, 17, 15, 16, 17, 18, 16, 15, 17, 16, 17, 16, 17, 18, 17, 13, 14, 12, 12, 12, 13, 14, 14, 12, 14, 14, 13, 14, 12, 13, 14, 13, 13, 14, 13, 15, 13, 13, 13, 13, 13, 12, 12, 12, 12, 13, 13, 12, 12, 12, 13, 14, 12, 12, 12, 14, 13, 9, 8, 9, 9, 9, 9, 7, 7, 7, 6, 9, 9, 7, 6, 7, 5, 6, 12, 12, 11, 11, 9, 9, 11, 10, 8, 9, 8, 8, 7, 7, 12, 12, 11, 11, 10, 9, 8, 9, 7, 7, 6, 2, 2, 3, 6, 5, 6, 6, 6, 5, 6, 7, 6, 7, 10, 10, 9, 10, 10, 9, 10, 9, 6, 5, 5, 6, 5, 6, 6, 6, 6, 5, 7, 6, 6, 7, 3, 3, 3, 2, 2, 4, 4, 2, 2, 6, 5, 3, 3, 2, 3, 18, 18, 18, 18, 17, 18, 19, 18, 7, 6, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 5, 5, 4, 4, 5, 6, 7, 5, 5, 3, 5, 4, 4, 5, 2, 3, 4, 4, 5, 4, 5, 4, 4, 5, 4, 4, 5, 5, 3, 5, 4, 6, 5, 4, 6, 6, 6, 6, 5, 4, 5, 5, 3, 5, 4, 5, 4, 5, 4, 4, 4, 4, 6, 3, 3, 4, 3, 5, 4, 5, 4, 5, 5, 4, 3, 4, 4, 4, 4, 4, 4, 17, 16, 14, 16, 16, 16, 17, 16, 17, 13, 15, 13, 14, 14, 13, 13, 12, 14, 14, 14, 13, 14, 13, 12, 12, 13, 14, 13, 14, 13, 12, 13, 5, 3, 4, 8, 7, 10, 10, 9, 9, 10, 10, 10, 10, 10, 10, 10, 11, 11, 8, 11, 8, 7, 6, 11, 11, 11, 11, 13, 10, 10, 11, 7, 7, 7, 7, 6, 7, 11, 12, 8, 8, 8, 9, 10, 10, 11, 11, 10, 12, 12, 6, 7, 6, 10, 10, 10, 12, 4, 5, 4, 5, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 5, 4, 5, 5, 6, 4, 4, 7, 5, 5, 4, 4, 4, 4, 3, 3, 3, 5, 5, 4, 5, 4, 3, 5, 5, 5, 4, 4, 5, 4, 5, 5, 5, 6, 5, 5, 5, 5, 5, 3, 4, 3, 5, 5, 5, 5, 4, 4, 5, 5, 10, 11, 11, 11, 6, 9, 10, 10, 11, 11, 10, 10, 9, 10, 10, 9, 10, 5, 5, 5, 5, 11, 11, 11, 6, 6, 11, 11, 10, 10, 6, 4, 5, 5, 5, 6, 5, 6, 6, 2, 3, 3, 5, 10, 12, 11, 11, 10, 9, 11, 9, 12, 13, 13, 13, 14, 13, 13, 10, 11, 10, 10, 10, 10, 15, 12, 8, 6, 6, 9, 3, 4, 3, 3, 2, 4, 5, 2, 3, 14, 12, 7, 5, 4, 13, 13, 13, 13, 14, 14, 14, 15, 14, 15, 12, 12, 12, 12, 11, 11, 13, 13, 13, 13, 14, 14, 9, 10, 9, 10, 10, 12, 12, 11, 12, 11, 13, 13, 13, 12, 17, 14, 10, 10, 10, 9, 12, 15, 11, 8, 17, 17, 17, 17, 17, 11, 13, 11, 10, 11, 10, 11, 11, 11, 11, 8, 13, 12, 12, 11, 12, 11, 10, 8, 10, 9, 15, 11, 9, 13, 10, 15, 14, 15, 14, 17, 15, 15, 13, 12, 15, 17, 14, 14, 13, 12, 14, 14, 15, 14, 17, 17, 15, 12, 13, 13, 11, 13, 13, 15, 11, 12, 11, 13, 14, 11, 12, 13, 15, 17, 14, 11, 12, 11, 13, 16, 13, 9, 8, 11, 8, 7, 10, 8, 10, 7, 7, 9, 9, 10, 12, 10, 12, 8, 8, 9, 9, 12, 17, 6, 8, 7, 9, 9, 7, 8, 8, 9, 11, 10, 11, 9, 9, 7, 13, 8, 11, 13, 3, 4, 6, 5, 18, 16, 16, 17, 16, 16, 17, 16, 16, 16, 17, 14, 10, 13, 6, 6, 6, 8, 8, 8, 8, 8, 10, 9, 7, 7, 6, 8, 8, 7, 7, 7, 7, 8, 8, 10, 9, 7, 8, 7, 6, 7, 12, 11, 11, 15, 14, 12, 12, 13, 11, 11, 10, 11, 10, 10, 10, 11, 11, 12, 11, 10, 10, 11, 10, 9, 7, 7, 7, 8, 8, 8, 8, 9, 9, 10, 9, 10, 5, 7, 7, 7, 5, 5, 5, 5, 5, 7, 6, 6, 5, 5, 6, 5, 5, 5, 8, 7, 7, 8, 7, 8, 8, 8, 9, 8, 9, 9, 9, 9, 9, 9, 8, 10, 11, 11, 12, 9, 10, 9, 5, 6, 8, 8, 6, 5, 5, 6, 6, 7, 7, 6, 7, 8, 8, 7, 7, 9, 9, 9, 9, 7, 7, 6, 8, 9, 10, 9, 6, 7, 10, 9, 9, 6, 7, 16, 14, 13, 12, 13, 13, 14, 16, 15, 15, 16, 14, 18, 15, 15, 12, 12, 11, 13, 12, 13, 14, 16, 16, 16, 14, 18, 18, 15, 15, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 7, 9, 9, 9, 9, 8, 10, 10, 7, 6, 7, 7, 7, 8, 7, 8, 9, 10, 7, 6, 8, 5, 6, 6, 10, 10, 8, 8, 8, 9, 8, 10, 11, 10, 13, 12, 11, 12, 12, 11, 9, 9, 11, 11, 9, 9, 10, 15, 17, 17, 18, 17, 17, 15, 17, 18, 17, 17, 18, 17, 15, 17, 17, 15, 17, 17, 14, 16, 17, 14, 18, 17, 16, 17, 8, 19, 7, 10, 9, 18, 7, 8, 8, 17, 10, 8, 9, 17, 10, 10, 15, 15, 17, 16, 18, 18, 17, 17, 18, 17, 15, 15, 16, 15, 16, 18, 16, 15, 18, 16, 16, 16, 15, 17, 18, 15, 15, 17, 15, 15, 15, 18, 16, 17, 18, 16, 16, 15, 16, 16, 15, 16, 15, 18, 17, 17, 17, 18, 17, 17, 19, 17, 17, 19, 18, 10, 11, 10, 10, 9, 8, 8, 6, 7, 8, 6, 6, 15, 15, 13, 13, 13, 4, 5, 5, 5, 4, 5, 4, 4, 5, 4, 4, 2, 3, 2, 4, 3, 4, 2, 3, 3, 5, 2, 5, 3, 5, 4, 2, 5, 3, 6, 5, 3, 5, 5, 6, 4, 6, 2, 3, 3, 4, 4, 3, 3, 3, 4, 3, 4, 3, 3, 5, 5, 5, 5, 4, 5, 4, 4, 4, 4, 3, 17, 17, 17, 18, 17, 17, 16, 15, 18, 18, 18, 18, 17, 16, 16, 17, 17, 3, 4, 4, 4, 6, 3, 3, 5, 4, 5, 4, 4, 3, 5, 4, 4, 7, 11, 5, 10, 9, 9, 5, 6, 7, 6, 11, 8, 11, 6, 7, 7, 7, 5, 5, 12, 11, 11, 14, 14, 14, 18, 19, 18, 15, 14, 16, 15, 17, 17, 19, 15, 17, 14, 15, 15, 15, 15, 15, 15, 18, 16, 7, 4, 4, 4, 4, 5, 5, 3, 5, 5, 5, 6, 4, 3, 3, 3, 9, 2, 4, 4, 3, 3, 4, 4, 4, 5, 5, 5, 4, 3, 5, 5, 6, 3, 3, 4, 4, 5, 4, 6, 4, 4, 4, 3, 3, 6, 7, 5, 5, 4, 2, 5, 4, 2, 3, 3, 3, 3, 3, 3, 3, 3, 5, 6, 4, 7, 4, 3, 3, 3, 5, 3, 4, 2, 4, 5, 4, 3, 3, 3, 3, 2, 5, 2, 12, 13, 12, 10, 16, 15, 17, 17, 9, 16, 17, 16, 3, 16, 3, 5, 3, 3, 2, 4, 5]

In [30]:
#1 a) to find the frequencies of Age column 

age_dict ={}
for i in age_list:
    if i not in age_dict.keys():
        age_dict[i] = 1
    else:
        age_dict[i] = age_dict[i] +1
print(age_dict)

{4: 228, 3: 157, 6: 245, 5: 271, 14: 271, 13: 315, 12: 287, 10: 258, 7: 231, 9: 257, 11: 282, 8: 198, 16: 198, 17: 221, 18: 139, 19: 19, 15: 264, 20: 1, 2: 56}

In [76]:
import sys
sys.set_int_max_str_digits(0)
sys.setrecursionlimit(4000)
count = len(age_list) # gives the total count of Age values.
def factorialnos(n):  #function to find factorial of a given number
    if n == 0:
        return 1
    else:
        return n * factorialnos(n-1)


denominator =1
for vals in age_dict.values():
    result = factorialnos(vals)
    denominator *=result

prob = 1
for vals in age_dict.values():
    result = vals/count
    #sum = sum + result
    prob*= result

numerator = factorialnos(count)
res = (numerator//denominator)   # formula to find multinomial ----> ((n!/ x1!,x2!....xk!) * p1x1.p2x2.p3x3....pkxk) where x1+x2+...xk = n and p1x1+p2x2+p3x3....+pkxk = 1
from decimal import Decimal
multinomial = res*Decimal(prob) 
print(multinomial)

4.664244339928473642307697605E+4699

In [ ]:
import random
import math

def multinomial_distribution(num_trials, probabilities):
 
    
    # Check if probabilities sum up to approximately 1
    if abs(sum(probabilities) - 1) > 1e-6:
        raise ValueError("Probabilities must sum up to approximately 1.")
    
    # Initialize counts for each outcome
    counts = [0] * len(probabilities)
    
    # Generate samples
    for _ in range(num_trials):
        rand = random.random()  # Generate a random number between 0 and 1
        cumulative_prob = 0
        for i, prob in enumerate(probabilities):
            cumulative_prob += prob
            if rand < cumulative_prob:
                counts[i] += 1
                break
    
    return counts

# Function to calculate factorial
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

# Function to calculate multinomial coefficient using factorials
def multinomial_coefficient(n, counts):
    coefficient = factorial(n)
    for count in counts:
        coefficient //= factorial(count)
    return coefficient

# Function to calculate multinomial probability
def multinomial_probability(n, counts, probabilities):
    coefficient = multinomial_coefficient(n, counts)
    product = 1
    for count, prob in zip(counts, probabilities):
        product = prob * count
    return coefficient * product

# Example usage:
num_trials = 10
probabilities = distribution_final  # Example probabilities
counts = multinomial_distribution(num_trials, probabilities)
print("Counts for each outcome:", counts)

total_trials = sum(counts)
print("Total trials:", total_trials)

# Calculate multinomial probability for the observed counts
probability = multinomial_probability(total_trials, counts, probabilities)
print("Multinomial probability:", probability)